#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeatherApp.Droid.Resource", IsApplication=true)]

namespace WeatherApp.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020002
			public const int humidityText = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int humidtyLabel = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int locationLabel = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int locationText = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int relativeLayout1 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int sunriseLabel = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int sunriseText = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int sunsetLabel = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int sunsetText = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int tempLabel = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int tempText = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int visibilityLabel = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int visibilityText = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int weatherBtn = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int windLabel = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int windText = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int zipCodeEntry = 2130837522;
			
			// aapt resource value: 0x7F020000
			public const int ZipCodeLabel = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int ZipCodeSearchLabel = 2130837505;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050000
			public const int Theme_Custom = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Theme_Custom1 = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
